services:
  mongo:
    image: mongo:7
    container_name: taller2-mongo
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: taller2-backend
    restart: unless-stopped
    environment:
      PORT: 5000
      MONGO_URI: mongodb://mongo:27017/taller2_arqui
      JWT_SECRET: change_this_secret
      JWT_EXPIRES_IN: 1d
      ALLOWED_ORIGINS: http://localhost,http://127.0.0.1,http://localhost:3000,http://127.0.0.1:3000
    depends_on:
      - mongo
    expose:
      - "5000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        API_INTERNAL_URL: http://backend:5000
    container_name: taller2-frontend
    restart: unless-stopped
    environment:
      API_INTERNAL_URL: http://backend:5000
    depends_on:
      - backend
    expose:
      - "3000"

  caddy:
    image: caddy:2.8-alpine
    container_name: taller2-caddy
    restart: unless-stopped
    depends_on:
      - frontend
      - backend
    environment:
      APP_DOMAIN: ${APP_DOMAIN}
      CADDY_EMAIL: ${CADDY_EMAIL}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config

volumes:
  mongo_data:
  caddy_data:
  caddy_config:
